# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='file_type',
        ),
    ]
